<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Tracked camera tool for OnAirTap (OpenVR version)</Description>
    <Company>milkydelta</Company>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>PCL</DefineConstants>
  </PropertyGroup>


  <ItemGroup>
    <Content Include="lib/comm.so" Condition="Exists('lib/comm.so')" Link="%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <None Include="lib/libopenvr_api.so" Link="%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <Content Include="lib/openvr_api.dll" Link="%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="licenses/*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>


  <!-- <ItemGroup>
    <PackageReference Include="Mono.Options" Version="6.12.0.148" />
  </ItemGroup> -->

</Project>
